### ISSUE TITLE
Custom Paths

### ISSUE THREAD

**Issue by GuacheSuede** [daedric/httpp#26]
Hi Thomas( @daedric ), 

how would one go about creating custom paths eg. /post/(id) ?

Thank You

**Comment by daedric** [comment]
Hi,
there is not facility to parse the query path, what I would probably do is use RE2 and do the dispatch in your callback (the one called by HTTPP).
If you're up to it you can also extend the RestDispatcher to accepts regex, it should be relatively trivial to add.

**Comment by GuacheSuede** [comment]
Are there currently any URL parsers in the source ?

**Comment by GuacheSuede** [comment]
@daedric , URL Parser + hook it up to request function, how abt that ? I can try to attempt it

**Comment by daedric** [comment]
Hi,
You must distinguish the HTTP protocol from what your API is understanding. HTTPP is parsing the HTTP request and give it to you, from there you can rebuild the initial URL if you need to (unlikely).
For instance, the server part of the URL will be in the `Host` header, the query path in the `uri` field in the `Request` class and the parameters will be in `query_params`

I suggest you to run the ping example with a debugger and explore the connection and request instance.

**Comment by GuacheSuede** [comment]
Do you know what file should i be looking at for request memebers ?

**Comment by daedric** [comment]
From the Connection pointer you get in the callback you've access to an instance of: https://github.com/daedric/httpp/blob/master/include/httpp/http/Request.hpp

**Comment by GuacheSuede** [comment]
@daedric how abt '/path/[int]/[string]' and dispatcher checks for it with an if ?

**Comment by daedric** [comment]
then you have to implement it. it is specific to your program not to http.
You can expand the RestDispatcher to handle a regexp in the `Request.uri` field

**Comment by GuacheSuede** [comment]
was thinking of expanding Dispatcher for that.
Quick question, static_assert(sizeof...(method) > 0, "At least one method is required");
what does the 3 dots after sizeof mean ?

**Comment by daedric** [comment]
You've the explaination there: https://en.wikipedia.org/wiki/Variadic_template
