### ISSUE TITLE
cant use vcpkg download it?

### ISSUE THREAD

**Issue by changtj** [daedric/httpp#30]
i use vcpkg to download it ,  and failed.

**Comment by daedric** [comment]
Unfortunately, I did not yet port HTTPP on windows.

**Comment by 0x7f** [comment]
I started porting it to Windows some time ago, but stopped (didn't have much time then). Is there interest in porting it? If so, I could try to continue porting.

**Comment by daedric** [comment]
I don't have a windows available ATM but I'm willing to work in this direction as well.

**Comment by daedric** [comment]
@0x7f would you be able to make a PR with the work you've started ?

**Comment by 0x7f** [comment]
@changtj sorry for the delay, but finally found time to port commonpp and httpp to windows:
https://github.com/daedric/commonpp/pull/7
https://github.com/daedric/httpp/pull/31

**Comment by daedric** [comment]
That's #^$% awesome !
I'll have a look asap, thanks a lot mate
