### ISSUE TITLE
 no .hpp file in the path /httpp/http/ ?

### ISSUE THREAD

**Issue by winnyrain** [daedric/httpp#33]
There are no .hpp files so that the code compile error.
Can you upload it ,thank you.

**Comment by daedric** [comment]
Will fix today. If you mean the error on the CI this is because I broke the commonpp vendoring.
Please note that the last tag should build.

Thanks for the report!

**Comment by daedric** [comment]
It should be fixed now, the CI will confirm it soon.

I need to do a big rework of everything related to CMake in HTTPP and its dependency. Currently I assume that it will be used in a third_party directory in a project as it currently is.
If you need the install/package rules I invite you to checkout the last release.
